finish the func delete post and delete comment
Chun-Ge/Shudong-Backend pull request #52
Opened 2018-05-23 08:59 UTC by Boyce-Lee

# what I done
## 1. finish the func deleting comment and post
## 2. fix some tiny errors in model/user_upvote_comment.go and model/user_upvote_post.go
## 3. add route map in route.go for deleting post and comment
```go
// in route.go
func registerCommentRoutes(app *iris.Application) {
	// redundant API "/comments" for "/posts/{postid:int min(1)}/comments"
	commentRoutes := app.Party("/post/{postid:int min(1)}").Party("/comments")
	commentRoutes.Use(middlewares.CheckLoginStatus)

	// add any subpath below
	// commentRoutes.Get("/", service.GetComments)
	commentRoutes.Delete("/{commentid:int min(1)}", service.DeleteComment)
}
```

2018-05-24 02:24 UTC, MarshallW906 commented on vendor/model/user_upvote_post.go
> +	return database.Orm.Table("user_upvot_post").Insert(
`user_upvote_post`? I mean, a missing `e`

2018-05-24 02:26 UTC, MarshallW906 requested changes
Everything's OK but a tiny spelling error. 👍

2018-05-26 07:09 UTC, Boyce-Lee commented on vendor/model/user_upvote_post.go
> +	return database.Orm.Table("user_upvot_post").Insert(
i has fix the error

2018-05-26 18:38 UTC, alexandrali3 submitted a review, later dismissed
plz separate the fixing part of route.go from this branch.

2018-05-27 04:04 UTC, MarshallW906 approved these changes

2018-05-28 16:07 UTC, merged